import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../"import React from 'react'
import { Toaster } from "@/components/ui/toaster";  //for sign-in
import AuthProvider from "@/content/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <AuthProvider>
      <body className={inter.className}>{children}</body>
      <Toaster />    
    </AuthProvider>
    </html>
  );
}
